"""Integration tests for pgloglens using Docker-generated PostgreSQL logs.

These tests validate pgloglens capabilities against real PostgreSQL logs
generated by a Docker container with comprehensive logging enabled.

Run with: pytest tests/test_integration.py -v --docker

Prerequisites:
  1. docker-compose up -d
  2. python tests/docker/generate_logs.py
  3. docker cp pgloglens-test-pg:/var/log/postgresql/postgresql.log tests/docker/
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List

import pytest

# Mark all tests in this module as integration tests
pytestmark = pytest.mark.integration

TESTS_DIR = Path(__file__).parent
DOCKER_LOG = TESTS_DIR / "docker" / "postgresql.log"
SAMPLE_LOG = TESTS_DIR / "sample_pg.log"


def _get_log_path() -> Path:
    """Get the appropriate log file for testing."""
    if DOCKER_LOG.exists():
        return DOCKER_LOG
    # Fall back to sample log for CI without Docker
    return SAMPLE_LOG


def _run_analysis(log_path: Path, **kwargs) -> Dict[str, Any]:
    """Run pgloglens analysis and return parsed JSON output."""
    from pgloglens.parser import LogParser
    from pgloglens.analyzer import Analyzer
    from pgloglens.rca import run_rca

    slow_threshold = kwargs.get("slow_query_threshold_ms", 100.0)

    parser = LogParser(
        slow_query_threshold_ms=slow_threshold,
        filter_database=kwargs.get("database"),
        filter_user=kwargs.get("user"),
    )

    analyzer = Analyzer(
        log_file_paths=[str(log_path)],
        slow_query_threshold_ms=slow_threshold,
        top_queries=kwargs.get("top_queries", 50),
        top_errors=kwargs.get("top_errors", 50),
    )

    entries = parser.parse_file(log_path, show_progress=False)
    result = analyzer.process_entries(entries)
    run_rca(result)

    return result


def _run_cli(args: List[str], log_path: Path | None = None) -> subprocess.CompletedProcess:
    """Run pgloglens CLI command."""
    if log_path is None:
        log_path = _get_log_path()

    cmd = [sys.executable, "-m", "pgloglens.cli"] + args + [str(log_path)]
    return subprocess.run(cmd, capture_output=True, text=True, cwd=TESTS_DIR.parent)


# =============================================================================
# Core Parsing Tests
# =============================================================================

class TestLogParsing:
    """Test log parsing functionality."""

    def test_parser_reads_file(self):
        """Parser should read log file without errors."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)
        assert result.total_entries > 0, "Should parse at least one entry"

    def test_timestamp_extraction(self):
        """Parser should extract timestamps correctly."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)
        assert result.time_range_start is not None
        assert result.time_range_end is not None
        assert result.time_range_end >= result.time_range_start

    def test_user_database_extraction(self):
        """Parser should extract user and database fields."""
        from pgloglens.parser import LogParser

        log_path = _get_log_path()
        parser = LogParser()
        entries = list(parser.parse_file(log_path, show_progress=False))

        entries_with_user = [e for e in entries if e.user]
        entries_with_db = [e for e in entries if e.database]

        assert len(entries_with_user) > 0, "Should extract user from some entries"
        assert len(entries_with_db) > 0, "Should extract database from some entries"

    def test_log_level_extraction(self):
        """Parser should extract log levels."""
        from pgloglens.parser import LogParser
        from pgloglens.models import LogLevel

        log_path = _get_log_path()
        parser = LogParser()
        entries = list(parser.parse_file(log_path, show_progress=False))

        levels = {e.log_level for e in entries}
        assert LogLevel.LOG in levels, "Should have LOG level entries"


# =============================================================================
# Slow Query Detection Tests
# =============================================================================

class TestSlowQueryDetection:
    """Test slow query detection and analysis."""

    def test_detects_slow_queries(self):
        """Should detect queries exceeding threshold."""
        log_path = _get_log_path()
        result = _run_analysis(log_path, slow_query_threshold_ms=100.0)
        assert len(result.slow_queries) > 0, "Should detect slow queries"

    def test_slow_query_statistics(self):
        """Slow queries should have valid statistics."""
        log_path = _get_log_path()
        result = _run_analysis(log_path, slow_query_threshold_ms=100.0)

        for sq in result.slow_queries:
            assert sq.count >= 1, "Count should be at least 1"
            assert sq.avg_duration_ms > 0, "Average duration should be positive"
            assert sq.max_duration_ms >= sq.min_duration_ms, "Max >= Min"
            assert sq.p50_duration_ms <= sq.p95_duration_ms <= sq.p99_duration_ms, "Percentiles ordered"

    def test_query_normalization(self):
        """Queries should be normalized (literals replaced)."""
        log_path = _get_log_path()
        result = _run_analysis(log_path, slow_query_threshold_ms=100.0)

        if result.slow_queries:
            for sq in result.slow_queries:
                # Normalized queries shouldn't have string literals
                assert "'" not in sq.normalized_query or "$" in sq.normalized_query, \
                    "Query should be normalized"

    def test_slow_queries_sorted_by_total_time(self):
        """Slow queries should be sorted by total duration."""
        log_path = _get_log_path()
        result = _run_analysis(log_path, slow_query_threshold_ms=100.0)

        if len(result.slow_queries) >= 2:
            for i in range(len(result.slow_queries) - 1):
                assert result.slow_queries[i].total_duration_ms >= result.slow_queries[i + 1].total_duration_ms


# =============================================================================
# Error Pattern Detection Tests
# =============================================================================

class TestErrorDetection:
    """Test error pattern detection."""

    def test_detects_errors(self):
        """Should detect error entries."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)
        assert len(result.error_patterns) > 0, "Should detect error patterns"

    def test_error_pattern_counts(self):
        """Error patterns should have valid counts."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)

        for ep in result.error_patterns:
            assert ep.count >= 1, "Error count should be at least 1"
            assert len(ep.sample_messages) >= 1, "Should have at least one sample"

    def test_sqlstate_extraction(self):
        """Should extract SQLSTATE codes from errors."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)

        errors_with_code = [ep for ep in result.error_patterns if ep.error_code]
        # Sample log should have errors with SQLSTATE codes
        assert len(errors_with_code) >= 0, "May have errors with SQLSTATE codes"


# =============================================================================
# Lock and Deadlock Detection Tests
# =============================================================================

class TestLockDetection:
    """Test lock wait and deadlock detection."""

    def test_detects_lock_events(self):
        """Should detect lock wait events."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)
        # Lock events may or may not be present depending on log
        assert isinstance(result.lock_events, list)

    def test_deadlock_detection(self):
        """Should detect deadlocks if present."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)
        assert result.deadlock_count >= 0, "Deadlock count should be non-negative"


# =============================================================================
# Connection Statistics Tests
# =============================================================================

class TestConnectionStats:
    """Test connection statistics extraction."""

    def test_connection_tracking(self):
        """Should track connection statistics."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)

        assert result.connection_stats is not None
        assert result.connection_stats.total_connections >= 0

    def test_auth_failure_detection(self):
        """Should detect authentication failures."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)
        # Auth failures may or may not be present
        assert result.connection_stats.auth_failures >= 0


# =============================================================================
# Checkpoint Analysis Tests
# =============================================================================

class TestCheckpointAnalysis:
    """Test checkpoint statistics extraction."""

    def test_checkpoint_detection(self):
        """Should detect checkpoint events."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)
        assert result.checkpoint_stats is not None

    def test_checkpoint_statistics(self):
        """Checkpoint stats should have valid values."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)

        cs = result.checkpoint_stats
        assert cs.count >= 0
        assert cs.warning_count >= 0


# =============================================================================
# Autovacuum Analysis Tests
# =============================================================================

class TestAutovacuumAnalysis:
    """Test autovacuum statistics extraction."""

    def test_autovacuum_detection(self):
        """Should detect autovacuum events."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)
        # Autovacuum events may or may not be present
        assert isinstance(result.autovacuum_stats, list)

    def test_autovacuum_table_extraction(self):
        """Should extract table names from autovacuum events."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)

        for av in result.autovacuum_stats:
            assert av.table, "Autovacuum should have table name"


# =============================================================================
# Temp File Analysis Tests
# =============================================================================

class TestTempFileAnalysis:
    """Test temp file statistics extraction."""

    def test_tempfile_detection(self):
        """Should detect temp file events."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)
        # Temp files may or may not be present
        assert isinstance(result.temp_files, list)

    def test_tempfile_size_extraction(self):
        """Should extract temp file sizes."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)

        for tf in result.temp_files:
            assert tf.size_bytes > 0, "Temp file should have size"


# =============================================================================
# RCA (Root Cause Analysis) Tests
# =============================================================================

class TestRCA:
    """Test rule-based root cause analysis."""

    def test_rca_runs(self):
        """RCA should run without errors."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)
        assert isinstance(result.rca_findings, list)

    def test_rca_findings_structure(self):
        """RCA findings should have required fields."""
        log_path = _get_log_path()
        result = _run_analysis(log_path)

        for finding in result.rca_findings:
            assert finding.rule_id, "Finding should have rule_id"
            assert finding.severity, "Finding should have severity"
            assert finding.title, "Finding should have title"
            assert finding.description, "Finding should have description"
            assert len(finding.recommendations) >= 1, "Finding should have recommendations"

    def test_rca_sorted_by_severity(self):
        """RCA findings should be sorted by severity."""
        from pgloglens.models import Severity

        log_path = _get_log_path()
        result = _run_analysis(log_path)

        severity_order = {
            Severity.CRITICAL: 0, Severity.HIGH: 1, Severity.MEDIUM: 2,
            Severity.LOW: 3, Severity.INFO: 4
        }

        for i in range(len(result.rca_findings) - 1):
            current = severity_order[result.rca_findings[i].severity]
            next_sev = severity_order[result.rca_findings[i + 1].severity]
            assert current <= next_sev, "Findings should be sorted by severity"


# =============================================================================
# Output Format Tests
# =============================================================================

class TestOutputFormats:
    """Test output format rendering."""

    def test_json_output(self):
        """JSON output should be valid JSON."""
        from pgloglens.reporter import render_json

        log_path = _get_log_path()
        result = _run_analysis(log_path)
        output = render_json(result)

        data = json.loads(output)
        assert "slow_queries" in data
        assert "error_patterns" in data
        assert "rca_findings" in data

    def test_markdown_output(self):
        """Markdown output should have expected sections."""
        from pgloglens.reporter import render_markdown

        log_path = _get_log_path()
        result = _run_analysis(log_path)
        output = render_markdown(result)

        assert "# pgloglens" in output
        assert "##" in output  # Should have sections

    def test_html_output(self):
        """HTML output should be valid HTML."""
        from pgloglens.reporter import render_html

        log_path = _get_log_path()
        result = _run_analysis(log_path)
        output = render_html(result)

        assert "<!DOCTYPE html>" in output
        assert "<html" in output
        assert "</html>" in output
        assert "<style>" in output  # Should be self-contained


# =============================================================================
# CLI Tests
# =============================================================================

class TestCLI:
    """Test CLI functionality."""

    def test_cli_analyze_runs(self):
        """CLI analyze command should run."""
        result = _run_cli(["analyze", "--format", "json"])
        assert result.returncode == 0, f"CLI failed: {result.stderr}"

    def test_cli_json_output(self):
        """CLI should produce valid JSON output."""
        result = _run_cli(["analyze", "--format", "json"])
        if result.returncode == 0:
            data = json.loads(result.stdout)
            assert "slow_queries" in data

    def test_cli_verbose_mode(self):
        """CLI verbose mode should show progress."""
        result = _run_cli(["analyze", "--format", "json", "--verbose"])
        assert result.returncode == 0

    def test_cli_slow_threshold(self):
        """CLI should respect slow query threshold."""
        result = _run_cli(["analyze", "--format", "json", "--slow-query-threshold", "5000"])
        assert result.returncode == 0

    def test_cli_top_queries(self):
        """CLI should respect top-queries limit."""
        result = _run_cli(["analyze", "--format", "json", "--top-queries", "5"])
        if result.returncode == 0:
            data = json.loads(result.stdout)
            assert len(data.get("slow_queries", [])) <= 5


# =============================================================================
# Filter Tests
# =============================================================================

class TestFiltering:
    """Test filtering functionality."""

    def test_database_filter(self):
        """Should filter by database name."""
        from pgloglens.parser import LogParser

        log_path = _get_log_path()
        parser = LogParser(filter_database="testdb")
        entries = list(parser.parse_file(log_path, show_progress=False))

        for e in entries:
            if e.database:
                assert e.database == "testdb"

    def test_user_filter(self):
        """Should filter by user name."""
        from pgloglens.parser import LogParser

        log_path = _get_log_path()
        parser = LogParser(filter_user="testuser")
        entries = list(parser.parse_file(log_path, show_progress=False))

        for e in entries:
            if e.user:
                assert e.user == "testuser"


# =============================================================================
# Format Detection Tests
# =============================================================================

class TestFormatDetection:
    """Test log format auto-detection."""

    def test_stderr_format_detection(self):
        """Should detect stderr format."""
        from pgloglens.parser import detect_format, LogFormat

        lines = [
            "2024-01-15 08:00:01.234 UTC [12345] LOG:  test message\n",
        ]
        assert detect_format(lines) == LogFormat.STDERR

    def test_json_format_detection(self):
        """Should detect JSON format."""
        from pgloglens.parser import detect_format, LogFormat

        lines = [
            '{"timestamp": "2024-01-15 08:00:01.234", "error_severity": "LOG", "message": "test"}\n',
        ]
        assert detect_format(lines) == LogFormat.JSONLOG

    def test_syslog_format_detection(self):
        """Should detect syslog format."""
        from pgloglens.parser import detect_format, LogFormat

        lines = [
            "Jan 15 08:00:01 host postgres[12345]: LOG:  test message\n",
        ]
        assert detect_format(lines) == LogFormat.SYSLOG


# =============================================================================
# Edge Case Tests
# =============================================================================

class TestEdgeCases:
    """Test edge cases and error handling."""

    def test_empty_log_handling(self, tmp_path):
        """Should handle empty log files."""
        from pgloglens.parser import LogParser

        empty_log = tmp_path / "empty.log"
        empty_log.write_text("")

        parser = LogParser()
        entries = list(parser.parse_file(empty_log, show_progress=False))
        assert entries == []

    def test_malformed_line_handling(self, tmp_path):
        """Should handle malformed log lines gracefully."""
        from pgloglens.parser import LogParser

        bad_log = tmp_path / "bad.log"
        bad_log.write_text("this is not a valid log line\n" * 10)

        parser = LogParser()
        # Should not raise an exception
        entries = list(parser.parse_file(bad_log, show_progress=False))
        # May or may not parse entries depending on format

    def test_mixed_format_handling(self, tmp_path):
        """Should handle logs with some valid and invalid lines."""
        from pgloglens.parser import LogParser

        mixed_log = tmp_path / "mixed.log"
        content = """garbage line
2024-01-15 08:00:01.234 UTC [12345] LOG:  valid message
more garbage
2024-01-15 08:00:02.234 UTC [12346] LOG:  another valid message
"""
        mixed_log.write_text(content)

        parser = LogParser()
        entries = list(parser.parse_file(mixed_log, show_progress=False))
        assert len(entries) >= 2, "Should parse valid lines"


# =============================================================================
# Performance Tests
# =============================================================================

class TestPerformance:
    """Test performance characteristics."""

    def test_streaming_memory_efficiency(self):
        """Parser should use streaming (generator) approach."""
        from pgloglens.parser import LogParser
        import types

        log_path = _get_log_path()
        parser = LogParser()
        result = parser.parse_file(log_path, show_progress=False)

        # Result should be a generator, not a list
        assert isinstance(result, types.GeneratorType), "Parser should return generator"
